#####################
# Octomap Generator
#####################
octomap:
    pointcloud_topic: "/semantic_pcl/semantic_pcl"
    #pointcloud_topic: "/camera/depth/points"
    #tree_type: COLOR_OCTREE 0 SEMANTICS_OCTREE_MAX 1 SEMANTICS_OCTREE_BAYESIAN 2
    tree_type: 1
    world_frame_id: "world"
    resolution: 0.05
    max_range: 5.0
    raycast_range: 2.0
    clamping_thres_min: 0.12
    clamping_thres_max: 0.97
    occupancy_thres: 0.5
    prob_hit: 0.7
    prob_miss: 0.4
    save_path : "~/map.bt"

#####################
# System Related Parameters
#####################
system/v_max: 1 #0.5 ##0.5
system/dyaw_max: 0.5
# check the relevant sdf file: depth_camera_new.sdf
system/camera/pitch: [0.0] #sensor_pitch: 0.0
system/camera/horizontal: [60.0] #sensor_hor_fov: 60
system/camera/vertical: [45.0] #sensor_ver_fov: 45
system/bbx/x: 0.1
system/bbx/y: 0.1
system/bbx/z: 0.1
system/bbx/overshoot: 0.5
system/localization/use_gazebo_ground_truth: true

# Gain Computation Parameters
nbvp/gain/free: 0.0
nbvp/gain/occupied: 0.0
nbvp/gain/unmapped: 1.0
nbvp/gain/area: 0.0
nbvp/gain/probabilistic: 0.0
nbvp/gain/range: 5 # Maximum distance of volumes to be considered for the gain computation (double, default: 1.0)
nbvp/gain/zero: 0.0
nbvp/gain/degressive_coeff: 0.5

inspection_throttle: 0.5
pcl_throttle: 0.33 # default 0.33
output/file/name: "gains.csv"

# Path Planning Parameters: rrt_planner.cpp
nbvp/tree/extension_range: 3
nbvp/tree/initial_iterations: 5
nbvp/tree/cuttoff_iterations: 200
nbvp/tree/exact_root: false
nbvp/dt: 0.1

# Exploration Loop: exploration_planner_node.cpp
exploration/log/on: true
exploration/dt: 2.0
exploration/num_iterations: 100

# Logging Parameters
nbvp/log/throttle: 0.25 # ?? 
nbvp/log/on: true

# Exploration Area for the manual Generated Area (CAD)
bbx/minX: -10.0
bbx/maxX: 10.0
bbx/minY: -10.0
bbx/maxY: 10.0
bbx/minZ: -10.0
bbx/maxZ: 10.0
bbx/softBounds: false

############
## Octomap Manager settings
############
tf_frame: "world"
robot_frame: "base_point_cloud"
resolution: 0.15
mesh_resolution: 1.0
visualize_max_z: 5.0
sensor_max_range: 8.0
map_publish_frequency: 0.2
probability_hit: 0.7
probability_miss: 0.4
threshold_min: 0.12
threshold_max: 0.97
threshold_occupancy: 0.7
treat_unknown_as_occupied: false
latch_topics: false
max_free_space: 0
min_height_free_space: 0
change_detection_enabled: false

# Planning Methods
# Volumetric 0
# Semantic Rear Side Voxel 1
# Pure_Entropy 2
# Average Entropy 3
# Semantic Rear side entropy 4 


/utility/method: 0
/output/file/name: "1.csv"
