#####################
# System Related Parameters
#####################
system/v_max: 1 #0.5 ##0.5
system/dyaw_max: 0.5
system/camera/pitch: [15.0] #sensor_pitch: 0.093
system/camera/horizontal: [58.0] #sensor_hor_fov: 60
system/camera/vertical: [45.0] #sensor_ver_fov: 45
system/bbx/x: 0.1
system/bbx/y: 0.1
system/bbx/z: 0.1
system/bbx/overshoot: 0.5

# Gain Computation Parameters
nbvp/gain/free: 0.0
nbvp/gain/occupied: 0.0
nbvp/gain/unmapped: 1.0
nbvp/gain/area: 0.0
nbvp/gain/probabilistic: 0.0
nbvp/gain/range: 1 # Maximum distance of volumes to be considered for the gain computation (double, default: 1.0) 
nbvp/gain/zero: 0.0
nbvp/gain/degressive_coeff: 0.5

inspection_throttle: 0.5
#pcl_throttle: 0.5 # default 0.33
output/file/name: "gains.csv"

# Path Planning Parameters
nbvp/tree/extension_range: 1
nbvp/tree/initial_iterations: 5
nbvp/tree/cuttoff_iterations: 200
nbvp/tree/exact_root: false
nbvp/dt: 0.1

# Logging Parameters
nbvp/log/throttle: 0.25 # ?? 
nbvp/log/on: true

# Exploration Area for the manual Generated Area (CAD)
bbx/minX: 10.0
bbx/maxX: 10.0
bbx/minY: -10.0
bbx/maxY: 10.0
bbx/minZ: -10.0
bbx/maxZ: 10.0
bbx/softBounds: false

############
## Octomap Manager settings
############
tf_frame: "world"
robot_frame: "base_point_cloud"
resolution: 0.15
mesh_resolution: 1.0
visualize_max_z: 5.0
sensor_max_range: 8.0
map_publish_frequency: 0.2
probability_hit: 0.7
probability_miss: 0.4
threshold_min: 0.12
threshold_max: 0.97
threshold_occupancy: 0.7
treat_unknown_as_occupied: false
latch_topics: false
max_free_space: 0
min_height_free_space: 0
change_detection_enabled: false

#Mavros related settings
/uav_1/mavros/local_position/frame_id: world           #(string, default: fcu) frame_id for message.
/uav_1/mavros/local_position/tf/send: true             #(bool, default: true)
/uav_1/mavros/local_position/tf/frame_id: world        #(string, default: local_origin) Origin frame_id for TF.
/uav_1/mavros/local_position/tf/child_frame_id: fcu    #(string, default: fcu) Child frame_id for TF.

# Planning Methods
# Volumetric 0
# Semantic Rear Side Voxel 1
# Pure_Entropy 2
# Average Entropy 3
# Semantic Rear side entropy 4 


/utility/method: 4
/output/file/name: "1.csv"


#/utility/method: 2
#/output/file/name: "2.csv"


#/utility/method: 3
#/output/file/name: "3.csv"


#/utility/method: 4
#/output/file/name: "4.csv"
